auto: true
server: true
permalink: none
paginate: 5
baseurl: "http://testeroids.github.com/Testeroids"
exclude:
- .gitignore
- README.md

prose:
  rooturl: ""
  metadata: 
    _posts/articles: |
      published: false
      layout: article
      title: Your Post Title
      abstract: Short summary of your article.
      author_twitter: 
      author: 
      categories:
      - articles
  metadata: 
    Pages: |
      published: false
      layout: article
      title: Your Post Title
      abstract: Short summary of your article.
      author_twitter: 
      author: 
      categories:
      - articles	  
      
# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : 'UA-39087937-1'
  getclicky :
    site_id :
