auto: true
server: true
permalink: none
paginate: 5
baseurl: "http://testeroids.github.com/Testeroids"
exclude:
- .gitignore
- README.md

prose:
  rooturl: ""
  metadata: 
    _posts/articles: |
      published: false
      layout: article
      title: Your Post Title
      abstract: Short summary of your article.
      author_twitter: 
      author: 
      categories:
      - articles
  metadata: 
    Pages: |
      published: false
      layout: article
      title: Your Post Title
      abstract: Short summary of your article.
      author_twitter: 
      author: 
      categories:
      - articles	  